apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{historisk.app}}
  namespace: "historisk"
  labels:
    team: "historisk"
spec:
  image: {{ image }}
  port: 8080
  azure:
    application:
      enabled: true
      tenant: {{azureTenant}}
      allowAllUsers: false
      claims:
        extra:
          - NAVident
        groups:
          - id: {{gruppe.admin}}
  webproxy: true
  vault:
    enabled: true
    paths:
      - kvPath: {{historisk.vault.credentials}}
        mountPath: /secrets/oracle/credentials
      - kvPath: {{historisk.vault.config}}
        mountPath: /secrets/oracle/config
  accessPolicy:
    inbound:
      rules:
        - application: historisk-pensjon
          namespace: historisk
          cluster: {{env}}-gcp
          permissions:
            roles:
              - dk_debkred_01
              - ps_belop_12
              - ps_krig_yrke_40
              - ps_person_01
              - ps_poeng_30
              - ps_tjenestepensjon_50
              - ps_vedtak_20
              - tep_ordn
              - tep_tekster_03
              # Historikk fra kommunesammenslåinger
              - psh_belop_12
              - psh_krig_yrke_40
              - psh_person_01
              - psh_poeng_30
              - psh_tjenestepensjon_50
              - psh_vedtak_20
        - application: historisk-tidsbegrenset-uforestonad
          namespace: historisk
          cluster: {{env}}-gcp
          permissions:
            roles:
              # Attføring
              - af_attfor_10
              - af_ledbl_nykey_16
              - af_lovhjemmel_11
              - af_tilskudd_12
              - af_utbetaling_15
              - afh_attfor_10
              - afh_ledbl_nykey_16
              - afh_lovhjemmel_11
              - afh_tilskudd_12
              - afh_utbetaling_15
              - di_koder_01
              - tk_g_omrade_70
              # Tidsbegrenset uførestønad
              - t_beregn_grl
              - t_delytelse
              - t_endring
              - t_endringsaarsak
              - t_grad
              - t_lopenr_fnr
              - t_rolle
              - t_stonad
              - t_tu
              - t_vedtak
              # Rehabiliteringspenger
              - rr_konto_nykey_16
              - rr_tilskudd_12
              - rr_utbetaling_15
              - rr_vedtak_10
              - rr_ytelse_11
              - rrh_konto_nykey_16
              - rrh_tilskudd_12
              - rrh_utbetaling_15
              - rrh_vedtak_10
              - rrh_ytelse_11
        - application: historisk-regnskap
          namespace: historisk
          cluster: {{env}}-gcp
          permissions:
            roles:
            - kp_konto_01
            - uh_person_01
            - uh_tilfelle_05
            - uh_utbet_10
            - uh_adresse_15
            - uh_tilbakebet_14
            - uh_konto_16
    outbound:
      rules: []
  strategy:
    type: RollingUpdate
  liveness:
    path: /actuator/health
    initialDelay: 20
    timeout: 5
    periodSeconds: 5
    failureThreshold: 50
  readiness:
    path: /actuator/health
    initialDelay: 20
    timeout: 5
    failureThreshold: 1000
  resources:
    limits:
      cpu: 1500m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 256Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /actuator/prometheus
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  ingresses:
    - {{historisk.appIngress}}
    - {{historisk.appInternalIngress}}
  env:
    - name: APP_DDL_AUTO
      value: "none"
    - name: APP_GRUPPE_ADMIN
      value: "{{gruppe.admin}}"
    - name: APP_TILGANGER_PENSJON
      value: "{{tilganger.pensjon}}"
    - name: APP_AUDIT_HOST
      value: "audit.nais"
    - name: APP_AUDIT_PORT
      value: "6514"
    - name: APP_UTTREKKSHENTERE_ROWID
      value: "dk_debkred_01"
    - name: spring_profiles_active
      value: "{{springProfiles}}"
    - name: "APP_DEFAULT_SCHEMA"
      value: "{{historisk.schema}}"
    - name: "APP_DDL_AUTO"
      value: "none"
