apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ks-exodus
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  port: 8080
  azure:
    application:
      enabled: true
  webproxy: true
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/creds/ks_infotrygd_q1-user
        mountPath: /var/run/secrets/oracle/creds
  accessPolicy:
    inbound:
      rules:
        - application: familie-ks-infotrygd-replika
          namespace: teamfamilie
          cluster: dev-gcp
          permissions:
            roles:
              - t_lopenr_fnr
              - t_stonad
              - t_vedtak
              - t_endring
              - t_rolle
              - t_ks
              - t_beregn_grl
              - sa_sak_10
    outbound:
      rules: []
  strategy:
    type: RollingUpdate
  liveness:
    path: /actuator/health
    initialDelay: 20
    timeout: 5
    periodSeconds: 5
    failureThreshold: 50
  readiness:
    path: /actuator/health
    initialDelay: 20
    timeout: 5
    failureThreshold: 1000
  resources:
    limits:
      cpu: 1500m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 256Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /actuator/prometheus
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  ingresses:
    - https://familie-ks-exodus.intern.dev.nav.no
    - https://familie-ks-exodus.dev-fss-pub.nais.io
  env:
    - name: APP_DATASOURCE_URL
      value: jdbc:oracle:thin:@a01dbfl058.adeo.no:1521/infotrygd_ksq_ha
    - name: APP_DATASOURCE_PLATFORM
      value: org.hibernate.dialect.OracleDialect
    - name: APP_DATASOURCE_DRIVER
      value: oracle.jdbc.driver.OracleDriver
    - name: APP_DATASOURCE_USERNAME_PATH
      value: /var/run/secrets/oracle/creds/username
    - name: APP_DATASOURCE_PASSWORD_PATH
      value: /var/run/secrets/oracle/creds/password
    - name: APP_DDL_AUTO
      value: "none"
    - name: APP_AUDIT_HOST
      value: "audit.nais"
    - name: APP_AUDIT_PORT
      value: "6514"
    - name: APP_UTTREKKSHENTERE_ROWID
      value: " "
    - name: spring_profiles_active
      value: "{{springProfiles}}"
    - name: APP_DEFAULT_SCHEMA
      value: INFOTRYGD_KSQ