name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
    permissions:
      packages: write
      contents: read
      id-token: write
  deploy_dev_ks:
    if: ${{ false }}
    needs:
      - build
    name: "Deploy til dev (teamfamilie)"
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - name: Deploy til dev-fss (teamfamilie)
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: dev-fss
          RESOURCE: nais/dev.yaml
          IMAGE: ${{ needs.build.outputs.image }}
          TELEMETRY: ${{ needs.build.outputs.telemetry }}
  deploy_prod_ks:
    if: ${{ false }}
    needs:
      - build
      - deploy_dev_ks
    name: "Deploy til prod (teamfamilie)"
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - name: Deploy til prod-fss (teamfamilie)
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: prod-fss
          RESOURCE: nais/prod.yaml
          IMAGE: ${{ needs.build.outputs.image }}
          TELEMETRY: ${{ needs.build.outputs.telemetry }}